"""create cloudcostops business tables

Revision ID: 0a1b510509a3
Revises: 
Create Date: 2026-08-09 14:10:33.096233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a1b510509a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('workflow_engine', sa.String(length=32), nullable=False),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('max_risk_level', sa.String(length=32), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('estimated_monthly_saving', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saving_rate', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_max_risk_level'), 'agent_runs', ['max_risk_level'], unique=False)
    op.create_index(op.f('ix_agent_runs_run_id'), 'agent_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('approval_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('operator', sa.String(length=128), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('approved_scope', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.run_id'], name=op.f('fk_approval_decisions_run_id_agent_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_decisions'))
    )
    op.create_index(op.f('ix_approval_decisions_decision'), 'approval_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_approval_decisions_run_id'), 'approval_decisions', ['run_id'], unique=False)
    op.create_table('generated_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('report_id', sa.String(length=128), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.run_id'], name=op.f('fk_generated_reports_run_id_agent_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_reports'))
    )
    op.create_index(op.f('ix_generated_reports_report_id'), 'generated_reports', ['report_id'], unique=True)
    op.create_index(op.f('ix_generated_reports_run_id'), 'generated_reports', ['run_id'], unique=False)
    op.create_table('optimization_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=True),
    sa.Column('env', sa.String(length=32), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('avg_cpu_utilization', sa.Float(), nullable=True),
    sa.Column('avg_memory_utilization', sa.Float(), nullable=True),
    sa.Column('avg_disk_utilization', sa.Float(), nullable=True),
    sa.Column('avg_gpu_utilization', sa.Float(), nullable=True),
    sa.Column('monthly_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('issue_type', sa.String(length=64), nullable=True),
    sa.Column('recommended_action', sa.String(length=128), nullable=True),
    sa.Column('estimated_monthly_saving', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('need_human_approval', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.run_id'], name=op.f('fk_optimization_items_run_id_agent_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_items')),
    sa.UniqueConstraint('run_id', 'resource_id', name='uq_optimization_items_run_resource')
    )
    op.create_index(op.f('ix_optimization_items_env'), 'optimization_items', ['env'], unique=False)
    op.create_index(op.f('ix_optimization_items_resource_id'), 'optimization_items', ['resource_id'], unique=False)
    op.create_index(op.f('ix_optimization_items_risk_level'), 'optimization_items', ['risk_level'], unique=False)
    op.create_index(op.f('ix_optimization_items_run_id'), 'optimization_items', ['run_id'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_label', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('key_output', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.run_id'], name=op.f('fk_workflow_steps_run_id_agent_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_steps')),
    sa.UniqueConstraint('run_id', 'step_id', name='uq_workflow_steps_run_step')
    )
    op.create_index(op.f('ix_workflow_steps_run_id'), 'workflow_steps', ['run_id'], unique=False)
    op.create_index(op.f('ix_workflow_steps_stage'), 'workflow_steps', ['stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_steps_stage'), table_name='workflow_steps')
    op.drop_index(op.f('ix_workflow_steps_run_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_optimization_items_run_id'), table_name='optimization_items')
    op.drop_index(op.f('ix_optimization_items_risk_level'), table_name='optimization_items')
    op.drop_index(op.f('ix_optimization_items_resource_id'), table_name='optimization_items')
    op.drop_index(op.f('ix_optimization_items_env'), table_name='optimization_items')
    op.drop_table('optimization_items')
    op.drop_index(op.f('ix_generated_reports_run_id'), table_name='generated_reports')
    op.drop_index(op.f('ix_generated_reports_report_id'), table_name='generated_reports')
    op.drop_table('generated_reports')
    op.drop_index(op.f('ix_approval_decisions_run_id'), table_name='approval_decisions')
    op.drop_index(op.f('ix_approval_decisions_decision'), table_name='approval_decisions')
    op.drop_table('approval_decisions')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_max_risk_level'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
