"""add agent run metadata fields

Revision ID: 22ef58e6aed5
Revises: 0a1b510509a3
Create Date: 2026-08-12 10:45:06.085876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ef58e6aed5'
down_revision: Union[str, Sequence[str], None] = '0a1b510509a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('llm_enabled', sa.Boolean(), nullable=True))
    op.add_column('agent_runs', sa.Column('llm_error', sa.Text(), nullable=True))
    op.add_column('agent_runs', sa.Column('approval_decision', sa.String(length=32), nullable=True))
    op.add_column('agent_runs', sa.Column('approval_operator', sa.String(length=128), nullable=True))
    op.add_column('agent_runs', sa.Column('approval_comment', sa.Text(), nullable=True))
    op.add_column('agent_runs', sa.Column('approved_scope', sa.String(length=128), nullable=True))
    op.add_column('agent_runs', sa.Column('billing_filename', sa.String(length=255), nullable=True))
    op.add_column('agent_runs', sa.Column('utilization_filename', sa.String(length=255), nullable=True))
    op.add_column('agent_runs', sa.Column('total_elapsed_time', sa.Float(), nullable=True))
    op.alter_column('agent_runs', 'run_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('agent_runs', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('agent_runs', 'workflow_engine',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               nullable=True)
    op.alter_column('agent_runs', 'estimated_monthly_saving',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('agent_runs', 'saving_rate',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.Float(),
               nullable=True)
    op.drop_index(op.f('ix_agent_runs_max_risk_level'), table_name='agent_runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agent_runs_max_risk_level'), 'agent_runs', ['max_risk_level'], unique=False)
    op.alter_column('agent_runs', 'saving_rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=8, scale=2),
               nullable=False)
    op.alter_column('agent_runs', 'estimated_monthly_saving',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('agent_runs', 'workflow_engine',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('agent_runs', 'status',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('agent_runs', 'run_id',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('agent_runs', 'total_elapsed_time')
    op.drop_column('agent_runs', 'utilization_filename')
    op.drop_column('agent_runs', 'billing_filename')
    op.drop_column('agent_runs', 'approved_scope')
    op.drop_column('agent_runs', 'approval_comment')
    op.drop_column('agent_runs', 'approval_operator')
    op.drop_column('agent_runs', 'approval_decision')
    op.drop_column('agent_runs', 'llm_error')
    op.drop_column('agent_runs', 'llm_enabled')
    # ### end Alembic commands ###
